5:47

diff --git a/web_server/3-redirection b/web_server/3-redirection
--- a/web_server/3-redirection
+++ b/web_server/3-redirection
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
 # Configures Nginx with 301 redirect for /redirect_me
 
-set -e
+set -e # fail fast, fail loud (on any error)
 
 # Install Nginx if missing
 apt-get update
 apt-get install -y nginx
 
-# Ensure web root
+# Ensure web root exists
 mkdir -p /var/www/html
 echo 'Holberton School for the win!' > /var/www/html/index.html
 
@@ -38,4 +38,3 @@ nginx -t
 
 # Restart
 service nginx restart
-EOF
